# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI master
on:  
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      OUTPUT_DIST: ${{ steps.packaging.outputs.OUTPUT_DIST }}
    steps:
      - id: packaging
        name: Pack distribution
        run: |
          mkdir dist
          echo "OUTPUT_DIST=$PWD/dist" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT_DIST: ${{ needs.job1.outputs.OUTPUT_DIST }}
        run: |
          echo "$OUTPUT_DIST"
          ls "$OUTPUT_DIST"
