# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI master
on:  
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT_DIR: ${{ steps.packaging.outputs.OUTPUT_DIR }}
    steps:
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Packing
    - id: packiging
      run: |
        mkdir dist
        ls
        echo "OUTPUT_DIR=$PWD/dist" >> "$GITHUB_OUTPUT"
        
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - env:
        OUTPUT_DIR: ${{ needs.build.outputs.OUTPUT_DIR }}
    - run: echo "$OUTPUT_DIR"
