# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI master
on:  
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write to file
        run: mkdir dist && echo $(date +%s) >> dist/test.txt

      - uses: actions/upload-artifact@v3
        with:
          name: lib-distribution
          path: dist
  
  job2:
    needs: job1
    environment:
      name: pypi
      url: https://pypi.org/project/dash-glue42/
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: List Before
        run: |
          ls
          
      - uses: actions/download-artifact@v3
        with:
          name: lib-distribution
          
      - name: List After
        run: |
          ls
          cat dist/test.txt
